##GET http://localhost:3000
##GET http://localhost:3000/usuarios
##GET http://localhost:3000/usuarios/0
##POST http://localhost:3000/usuarios
##PUT  http://localhost:3000/usuarios/0
##DELETE  http://localhost:3000/usuarios/0



